// GENERATED by scripts/build-images.mjs — do not edit by hand.
// Run `npm run images` to regenerate after changing the photo set.

export type Rendition = {
  width: number;
  height: number;
  jpg: string;
  webp: string | null;
  avif: string | null;
};

export type ImageAsset = {
  slug: string;
  alt: string;
  caption: string;
  width: number;
  height: number;
  ratio: number;
  source: string;
  renditions: Rendition[];
};

export const images = {
  "romo-black-flatbed-recycled-load-highway": {
    "slug": "romo-black-flatbed-recycled-load-highway",
    "alt": "Tractocamión de Romo's Transportes con plataforma cargada de material enfardado, en operación al atardecer junto a una carretera.",
    "caption": "Plataforma cargada — operación al atardecer",
    "width": 887,
    "height": 499,
    "ratio": 1.777778,
    "source": "Screenshot_20260916_200126_WhatsApp.jpg",
    "renditions": [
      {
        "width": 480,
        "height": 270,
        "jpg": "/images/hero/romo-black-flatbed-recycled-load-highway-480.jpg",
        "webp": "/images/hero/romo-black-flatbed-recycled-load-highway-480.webp",
        "avif": "/images/hero/romo-black-flatbed-recycled-load-highway-480.avif"
      },
      {
        "width": 768,
        "height": 432,
        "jpg": "/images/hero/romo-black-flatbed-recycled-load-highway-768.jpg",
        "webp": "/images/hero/romo-black-flatbed-recycled-load-highway-768.webp",
        "avif": "/images/hero/romo-black-flatbed-recycled-load-highway-768.avif"
      },
      {
        "width": 887,
        "height": 499,
        "jpg": "/images/hero/romo-black-flatbed-recycled-load-highway-887.jpg",
        "webp": "/images/hero/romo-black-flatbed-recycled-load-highway-887.webp",
        "avif": "/images/hero/romo-black-flatbed-recycled-load-highway-887.avif"
      }
    ]
  },
  "romo-black-flatbed-recycled-load-highway-mobile": {
    "slug": "romo-black-flatbed-recycled-load-highway-mobile",
    "alt": "Tractocamión de Romo's Transportes con plataforma cargada de material enfardado, en operación al atardecer junto a una carretera.",
    "caption": "Plataforma cargada — operación al atardecer",
    "width": 729,
    "height": 547,
    "ratio": 1.333333,
    "source": "Screenshot_20260916_200126_WhatsApp.jpg",
    "renditions": [
      {
        "width": 480,
        "height": 360,
        "jpg": "/images/hero/romo-black-flatbed-recycled-load-highway-mobile-480.jpg",
        "webp": "/images/hero/romo-black-flatbed-recycled-load-highway-mobile-480.webp",
        "avif": "/images/hero/romo-black-flatbed-recycled-load-highway-mobile-480.avif"
      },
      {
        "width": 729,
        "height": 547,
        "jpg": "/images/hero/romo-black-flatbed-recycled-load-highway-mobile-729.jpg",
        "webp": "/images/hero/romo-black-flatbed-recycled-load-highway-mobile-729.webp",
        "avif": "/images/hero/romo-black-flatbed-recycled-load-highway-mobile-729.avif"
      }
    ]
  },
  "romo-purple-flatbed-facility-wide": {
    "slug": "romo-purple-flatbed-facility-wide",
    "alt": "Tractocamión morado de Romo's Transportes con plataforma de tres ejes vacía, listo para cargar.",
    "caption": "Plataforma de tres ejes lista para carga",
    "width": 753,
    "height": 502,
    "ratio": 1.5,
    "source": "Screenshot_20260916_200253_WhatsApp.jpg",
    "renditions": [
      {
        "width": 480,
        "height": 320,
        "jpg": "/images/fleet/romo-purple-flatbed-facility-wide-480.jpg",
        "webp": "/images/fleet/romo-purple-flatbed-facility-wide-480.webp",
        "avif": "/images/fleet/romo-purple-flatbed-facility-wide-480.avif"
      },
      {
        "width": 753,
        "height": 502,
        "jpg": "/images/fleet/romo-purple-flatbed-facility-wide-753.jpg",
        "webp": "/images/fleet/romo-purple-flatbed-facility-wide-753.webp",
        "avif": "/images/fleet/romo-purple-flatbed-facility-wide-753.avif"
      }
    ]
  },
  "romo-purple-dry-van-mountains": {
    "slug": "romo-purple-dry-van-mountains",
    "alt": "Tractocamión morado de Romo's Transportes conectado a una caja seca, en un entorno de carretera y montaña.",
    "caption": "Caja seca — mercancía protegida del clima",
    "width": 843,
    "height": 562,
    "ratio": 1.5,
    "source": "Screenshot_20260916_200455_WhatsApp.jpg",
    "renditions": [
      {
        "width": 480,
        "height": 320,
        "jpg": "/images/fleet/romo-purple-dry-van-mountains-480.jpg",
        "webp": "/images/fleet/romo-purple-dry-van-mountains-480.webp",
        "avif": "/images/fleet/romo-purple-dry-van-mountains-480.avif"
      },
      {
        "width": 768,
        "height": 512,
        "jpg": "/images/fleet/romo-purple-dry-van-mountains-768.jpg",
        "webp": "/images/fleet/romo-purple-dry-van-mountains-768.webp",
        "avif": "/images/fleet/romo-purple-dry-van-mountains-768.avif"
      },
      {
        "width": 843,
        "height": 562,
        "jpg": "/images/fleet/romo-purple-dry-van-mountains-843.jpg",
        "webp": "/images/fleet/romo-purple-dry-van-mountains-843.webp",
        "avif": "/images/fleet/romo-purple-dry-van-mountains-843.avif"
      }
    ]
  },
  "romo-purple-dry-van-night": {
    "slug": "romo-purple-dry-van-night",
    "alt": "Tractocamión morado de Romo's Transportes con caja seca durante una operación nocturna, con las luces encendidas.",
    "caption": "Operación nocturna",
    "width": 1079,
    "height": 607,
    "ratio": 1.777778,
    "source": "Screenshot_20260916_200508_WhatsApp.jpg",
    "renditions": [
      {
        "width": 480,
        "height": 270,
        "jpg": "/images/operations/romo-purple-dry-van-night-480.jpg",
        "webp": "/images/operations/romo-purple-dry-van-night-480.webp",
        "avif": "/images/operations/romo-purple-dry-van-night-480.avif"
      },
      {
        "width": 768,
        "height": 432,
        "jpg": "/images/operations/romo-purple-dry-van-night-768.jpg",
        "webp": "/images/operations/romo-purple-dry-van-night-768.webp",
        "avif": "/images/operations/romo-purple-dry-van-night-768.avif"
      },
      {
        "width": 1079,
        "height": 607,
        "jpg": "/images/operations/romo-purple-dry-van-night-1079.jpg",
        "webp": "/images/operations/romo-purple-dry-van-night-1079.webp",
        "avif": "/images/operations/romo-purple-dry-van-night-1079.avif"
      }
    ]
  },
  "romo-fleet-night-branding": {
    "slug": "romo-fleet-night-branding",
    "alt": "Unidades de Romo's Transportes estacionadas durante una operación nocturna, con el emblema de la empresa visible en la puerta del tractocamión.",
    "caption": "Emblema Romo's en unidad propia",
    "width": 852,
    "height": 568,
    "ratio": 1.5,
    "source": "Screenshot_20260916_200422_WhatsApp.jpg",
    "renditions": [
      {
        "width": 480,
        "height": 320,
        "jpg": "/images/gallery/romo-fleet-night-branding-480.jpg",
        "webp": "/images/gallery/romo-fleet-night-branding-480.webp",
        "avif": "/images/gallery/romo-fleet-night-branding-480.avif"
      },
      {
        "width": 768,
        "height": 512,
        "jpg": "/images/gallery/romo-fleet-night-branding-768.jpg",
        "webp": "/images/gallery/romo-fleet-night-branding-768.webp",
        "avif": "/images/gallery/romo-fleet-night-branding-768.avif"
      },
      {
        "width": 852,
        "height": 568,
        "jpg": "/images/gallery/romo-fleet-night-branding-852.jpg",
        "webp": "/images/gallery/romo-fleet-night-branding-852.webp",
        "avif": "/images/gallery/romo-fleet-night-branding-852.avif"
      }
    ]
  },
  "romo-purple-flatbed-steel-pipes-warehouse": {
    "slug": "romo-purple-flatbed-steel-pipes-warehouse",
    "alt": "Tractocamión morado de Romo's Transportes con plataforma cargada de tubería de acero dentro de una nave industrial.",
    "caption": "Carga de tubería de acero en nave industrial",
    "width": 821,
    "height": 547,
    "ratio": 1.5,
    "source": "Screenshot_20260916_200146_WhatsApp.jpg",
    "renditions": [
      {
        "width": 480,
        "height": 320,
        "jpg": "/images/operations/romo-purple-flatbed-steel-pipes-warehouse-480.jpg",
        "webp": "/images/operations/romo-purple-flatbed-steel-pipes-warehouse-480.webp",
        "avif": "/images/operations/romo-purple-flatbed-steel-pipes-warehouse-480.avif"
      },
      {
        "width": 768,
        "height": 512,
        "jpg": "/images/operations/romo-purple-flatbed-steel-pipes-warehouse-768.jpg",
        "webp": "/images/operations/romo-purple-flatbed-steel-pipes-warehouse-768.webp",
        "avif": "/images/operations/romo-purple-flatbed-steel-pipes-warehouse-768.avif"
      },
      {
        "width": 821,
        "height": 547,
        "jpg": "/images/operations/romo-purple-flatbed-steel-pipes-warehouse-821.jpg",
        "webp": "/images/operations/romo-purple-flatbed-steel-pipes-warehouse-821.webp",
        "avif": "/images/operations/romo-purple-flatbed-steel-pipes-warehouse-821.avif"
      }
    ]
  },
  "romo-steel-structures-flatbed": {
    "slug": "romo-steel-structures-flatbed",
    "alt": "Plataforma con estructuras metálicas de gran dimensión aseguradas con bandas para su traslado.",
    "caption": "Estructura metálica asegurada sobre plataforma",
    "width": 897,
    "height": 598,
    "ratio": 1.5,
    "source": "Screenshot_20260916_200220_WhatsApp.jpg",
    "renditions": [
      {
        "width": 480,
        "height": 320,
        "jpg": "/images/operations/romo-steel-structures-flatbed-480.jpg",
        "webp": "/images/operations/romo-steel-structures-flatbed-480.webp",
        "avif": "/images/operations/romo-steel-structures-flatbed-480.avif"
      },
      {
        "width": 768,
        "height": 512,
        "jpg": "/images/operations/romo-steel-structures-flatbed-768.jpg",
        "webp": "/images/operations/romo-steel-structures-flatbed-768.webp",
        "avif": "/images/operations/romo-steel-structures-flatbed-768.avif"
      },
      {
        "width": 897,
        "height": 598,
        "jpg": "/images/operations/romo-steel-structures-flatbed-897.jpg",
        "webp": "/images/operations/romo-steel-structures-flatbed-897.webp",
        "avif": "/images/operations/romo-steel-structures-flatbed-897.avif"
      }
    ]
  },
  "romo-load-securing-rebar-warehouse": {
    "slug": "romo-load-securing-rebar-warehouse",
    "alt": "Personal con casco y chaleco de seguridad sobre una plataforma cargada con varilla de acero, durante la maniobra de sujeción.",
    "caption": "Maniobra de carga y sujeción",
    "width": 786,
    "height": 983,
    "ratio": 0.8,
    "source": "Screenshot_20260916_200135_WhatsApp.jpg",
    "renditions": [
      {
        "width": 480,
        "height": 600,
        "jpg": "/images/operations/romo-load-securing-rebar-warehouse-480.jpg",
        "webp": "/images/operations/romo-load-securing-rebar-warehouse-480.webp",
        "avif": "/images/operations/romo-load-securing-rebar-warehouse-480.avif"
      },
      {
        "width": 768,
        "height": 960,
        "jpg": "/images/operations/romo-load-securing-rebar-warehouse-768.jpg",
        "webp": "/images/operations/romo-load-securing-rebar-warehouse-768.webp",
        "avif": "/images/operations/romo-load-securing-rebar-warehouse-768.avif"
      },
      {
        "width": 786,
        "height": 983,
        "jpg": "/images/operations/romo-load-securing-rebar-warehouse-786.jpg",
        "webp": "/images/operations/romo-load-securing-rebar-warehouse-786.webp",
        "avif": "/images/operations/romo-load-securing-rebar-warehouse-786.avif"
      }
    ]
  },
  "romo-forage-load-highway": {
    "slug": "romo-forage-load-highway",
    "alt": "Dos plataformas cargadas y cubiertas circulando por una carretera nacional.",
    "caption": "Traslado por carretera nacional",
    "width": 800,
    "height": 450,
    "ratio": 1.777778,
    "source": "Screenshot_20260916_200204_WhatsApp.jpg",
    "renditions": [
      {
        "width": 480,
        "height": 270,
        "jpg": "/images/routes/romo-forage-load-highway-480.jpg",
        "webp": "/images/routes/romo-forage-load-highway-480.webp",
        "avif": "/images/routes/romo-forage-load-highway-480.avif"
      },
      {
        "width": 768,
        "height": 432,
        "jpg": "/images/routes/romo-forage-load-highway-768.jpg",
        "webp": "/images/routes/romo-forage-load-highway-768.webp",
        "avif": "/images/routes/romo-forage-load-highway-768.avif"
      },
      {
        "width": 800,
        "height": 450,
        "jpg": "/images/routes/romo-forage-load-highway-800.jpg",
        "webp": "/images/routes/romo-forage-load-highway-800.webp",
        "avif": "/images/routes/romo-forage-load-highway-800.avif"
      }
    ]
  },
  "romo-forage-load-yard": {
    "slug": "romo-forage-load-yard",
    "alt": "Plataformas con carga agrícola enfardada durante una operación de transporte.",
    "caption": "Carga agrícola enfardada",
    "width": 657,
    "height": 438,
    "ratio": 1.5,
    "source": "Screenshot_20260916_200345_WhatsApp.jpg",
    "renditions": [
      {
        "width": 480,
        "height": 320,
        "jpg": "/images/gallery/romo-forage-load-yard-480.jpg",
        "webp": "/images/gallery/romo-forage-load-yard-480.webp",
        "avif": "/images/gallery/romo-forage-load-yard-480.avif"
      },
      {
        "width": 657,
        "height": 438,
        "jpg": "/images/gallery/romo-forage-load-yard-657.jpg",
        "webp": "/images/gallery/romo-forage-load-yard-657.webp",
        "avif": "/images/gallery/romo-forage-load-yard-657.avif"
      }
    ]
  },
  "romo-black-flatbed-palletized-load": {
    "slug": "romo-black-flatbed-palletized-load",
    "alt": "Tractocamión con plataforma cargada de mercancía paletizada en una instalación industrial.",
    "caption": "Mercancía paletizada sobre plataforma",
    "width": 608,
    "height": 405,
    "ratio": 1.5,
    "source": "Screenshot_20260916_200408_WhatsApp.jpg",
    "renditions": [
      {
        "width": 480,
        "height": 320,
        "jpg": "/images/gallery/romo-black-flatbed-palletized-load-480.jpg",
        "webp": "/images/gallery/romo-black-flatbed-palletized-load-480.webp",
        "avif": "/images/gallery/romo-black-flatbed-palletized-load-480.avif"
      },
      {
        "width": 608,
        "height": 405,
        "jpg": "/images/gallery/romo-black-flatbed-palletized-load-608.jpg",
        "webp": "/images/gallery/romo-black-flatbed-palletized-load-608.webp",
        "avif": "/images/gallery/romo-black-flatbed-palletized-load-608.avif"
      }
    ]
  },
  "romo-white-flatbed-workshop": {
    "slug": "romo-white-flatbed-workshop",
    "alt": "Tractocamión blanco conectado a una plataforma de tres ejes dentro de una nave de mantenimiento.",
    "caption": "Unidad y plataforma en nave de mantenimiento",
    "width": 1620,
    "height": 1080,
    "ratio": 1.5,
    "source": "Screenshot_20260916_200228_WhatsApp.jpg",
    "renditions": [
      {
        "width": 480,
        "height": 320,
        "jpg": "/images/gallery/romo-white-flatbed-workshop-480.jpg",
        "webp": "/images/gallery/romo-white-flatbed-workshop-480.webp",
        "avif": "/images/gallery/romo-white-flatbed-workshop-480.avif"
      },
      {
        "width": 768,
        "height": 512,
        "jpg": "/images/gallery/romo-white-flatbed-workshop-768.jpg",
        "webp": "/images/gallery/romo-white-flatbed-workshop-768.webp",
        "avif": "/images/gallery/romo-white-flatbed-workshop-768.avif"
      },
      {
        "width": 1080,
        "height": 720,
        "jpg": "/images/gallery/romo-white-flatbed-workshop-1080.jpg",
        "webp": "/images/gallery/romo-white-flatbed-workshop-1080.webp",
        "avif": "/images/gallery/romo-white-flatbed-workshop-1080.avif"
      }
    ]
  },
  "romo-scrap-load-flatbed": {
    "slug": "romo-scrap-load-flatbed",
    "alt": "Plataforma con carga de material metálico cubierta y asegurada para su traslado.",
    "caption": "Material metálico cubierto y asegurado",
    "width": 785,
    "height": 523,
    "ratio": 1.5,
    "source": "Screenshot_20260916_200308_WhatsApp.jpg",
    "renditions": [
      {
        "width": 480,
        "height": 320,
        "jpg": "/images/gallery/romo-scrap-load-flatbed-480.jpg",
        "webp": "/images/gallery/romo-scrap-load-flatbed-480.webp",
        "avif": "/images/gallery/romo-scrap-load-flatbed-480.avif"
      },
      {
        "width": 768,
        "height": 512,
        "jpg": "/images/gallery/romo-scrap-load-flatbed-768.jpg",
        "webp": "/images/gallery/romo-scrap-load-flatbed-768.webp",
        "avif": "/images/gallery/romo-scrap-load-flatbed-768.avif"
      },
      {
        "width": 785,
        "height": 523,
        "jpg": "/images/gallery/romo-scrap-load-flatbed-785.jpg",
        "webp": "/images/gallery/romo-scrap-load-flatbed-785.webp",
        "avif": "/images/gallery/romo-scrap-load-flatbed-785.avif"
      }
    ]
  },
  "romo-fleet-lineup-street": {
    "slug": "romo-fleet-lineup-street",
    "alt": "Tractocamiones de Romo's Transportes estacionados, listos para iniciar operación.",
    "caption": "Unidades listas para salir a ruta",
    "width": 803,
    "height": 535,
    "ratio": 1.5,
    "source": "Screenshot_20260916_200156_WhatsApp.jpg",
    "renditions": [
      {
        "width": 480,
        "height": 320,
        "jpg": "/images/gallery/romo-fleet-lineup-street-480.jpg",
        "webp": "/images/gallery/romo-fleet-lineup-street-480.webp",
        "avif": "/images/gallery/romo-fleet-lineup-street-480.avif"
      },
      {
        "width": 768,
        "height": 512,
        "jpg": "/images/gallery/romo-fleet-lineup-street-768.jpg",
        "webp": "/images/gallery/romo-fleet-lineup-street-768.webp",
        "avif": "/images/gallery/romo-fleet-lineup-street-768.avif"
      },
      {
        "width": 803,
        "height": 535,
        "jpg": "/images/gallery/romo-fleet-lineup-street-803.jpg",
        "webp": "/images/gallery/romo-fleet-lineup-street-803.webp",
        "avif": "/images/gallery/romo-fleet-lineup-street-803.avif"
      }
    ]
  }
} as const satisfies Record<string, ImageAsset>;

export type ImageSlug = keyof typeof images;

export const excludedSources = [
  {
    "file": "Screenshot_20260916_200332_WhatsApp.jpg",
    "reason": "Encuadre saturado (agua estancada, tarimas suetas) y señalización de un tercero como elemento más legible. Pendiente de decisión del propietario."
  }
] as const;
